### ISSUE TITLE
Add FTP Service

### ISSUE THREAD

**Issue by omercnet** [Cymmetria/honeycomb_plugins#28]
* Provide banner of a common FTP service
* Allow basic commands on a mock filesystem (consider keeping it as a dict to avoid actual exploitation)
* Alerts: Muted alert on basic interaction, Alert on file upload

**Comment by Sleeptime17** [comment]
Didn't @lorg mention he wanted it to be a UNIX-y FTP banner?
Active alert - attempted path traversal?
Should this service also be compatible with MR? Can't remember if @lorg said that.

**Comment by Sleeptime17** [comment]
"UNIX-y" as in Linux instead of Windows. I'm mentioning him because I'm not sure if he wanted it that way or the other way around. A common Linux service would work.

There are no recent RCEs on FTP services unfortunately (5+ years I think). There seem to be some RCE on FTP *clients*, but that's not what we're here for ;)

**Comment by Sleeptime17** [comment]
Scratch that last comment, I'm pretty sure he meant the Telnet service.
That does leave me wondering why he wants an additional FTP service though? MR already has one.

**Comment by omercnet** [comment]
MR has a built in one, need to make it a custom service compatible with honeycomb 
I think @dekelb mentioned the internal codebase has something we're able to use right away
