### ISSUE TITLE
detect fileless malware

### ISSUE THREAD

**Issue by jjjan** [Cymmetria/honeycomb_plugins#42]
Could you make modules to detect fileless malware and capture it to folder. also capture any script is useful.
and at least would be great to port honeycomb to work on windows.

**Comment by omercnet** [comment]
hi @jjjan the concept of a honenypot is to mimic some service/application, if you have an idea for an exploitable service that would lure an attacker to deploy fileless malware on it we'd love to hear about it

honeycomb hasn't been tested much on windows but since it's python it should work for the mot part, give it a try and let us know if something's not working
